### ISSUE TITLE
T13 - Elaboração da modelagem do processo.

### ISSUE THREAD

**Issue by augustovilarins** [conosco/conosco-api#13]
T13 - Elaboração da modelagem do processo.
---
### Descrição:
Elaborar a modelagem do processo de desenvolvimento adotado pela equipe .

**Comment by AnaCarolcs** [comment]
A modelagem foi feita no Bizagi. Consta nos documentos do projeto, entretanto, apenas a modelagem da primeira etapa possui os artefatos detalhados
