### ISSUE TITLE
T19 - Criar diagrama de pacote 

### ISSUE THREAD

**Issue by AnaCarolcs** [conosco/conosco-api#19]
# T19 - Criar diagrama de pacote
---
### Descrição:
Criação do diagrama de pacote. Trata-se de um diagrama estrutural, estático, o qual permite organizar o sistema como se representasse uma visão em módulos.

### Tarefas 
- [x] Estudar a estrutura do diagrama
- [x] Planejar a organização do projeto
- [ ] Criar o diagrama

**Comment by djorkaeffalexandre** [comment]
O diagrama de pacote do front-end foi concluído.

**Comment by augustovilarins** [comment]
@gustavo2795  como que tá o do backend?
