### ISSUE TITLE
T22 - Criar Quadro de Conhecimento

### ISSUE THREAD

**Issue by vitorl-s** [conosco/conosco-api#22]
# T21 - Criar Quadro de Conhecimento
---
### Descrição:
Criação do Quadro de Conhecimento. Tem a finalidade de observar o nível de conhecimento das tecnologias que a equipe possui

### Tarefas
- [x] Criar Quadro de Conhecimento

**Comment by guilhermesiqueira** [comment]
Quadro de conhecimento criado e atualizado a cada sprint, estando disponível no drive.
