### ISSUE TITLE
US03 - Logar no sistema via e-mail

### ISSUE THREAD

**Issue by gustavo2795** [conosco/conosco-api#32]
# US03 - Logar no sistema - via e-mail
---
### Descrição:
Eu, como usuário, desejo fazer login no sistema via e-mail
--

### Critérios de Aceitação
Critérios de aceitação para a Issue ser aceita.
- [x] Ser possível logar no sistema
- [x] Validar se campo de e-mail e senha estão preenchidos

**Estimativa de Duração** : 3 pontos

**Comment by guilhermesiqueira** [comment]
Issue fechada no repositório [conosco-app](https://github.com/conosco/conosco-app).
